### PR TITLE
Add PHPStan settings

### PR DESCRIPTION
**Pull request by ernilambar**
Fixes https://github.com/wp-cli/wp-cli-tests/issues/203

- Add required composer packages for PHPStan
- Add `szepeviktor/phpstan-wordpress` as PHPStan extension for WordPress
- Add script to run test `"phpstan": "run-phpstan-tests",`
- Add `run-phpstan-tests` file in bin folder

### CODE REVIEW

**Comment by ernilambar** [comment]
Test repo - https://github.com/ernilambar/database-command/pull/15

Sample neon file:

```neon
parameters:
  level: 0
  paths:
    - command.php
    - src/
  scanFiles:
    - command.php
  treatPhpDocTypesAsCertain: false

```

**Comment by ernilambar** [comment]
Looks like PHPStan cannot be installed in PHP 7.1. 🤔

**Comment by swissspidy** [comment]
Ah yes, it has different PHP version requirements... Forgot about that when I opened the issue.

**Comment by ernilambar** [comment]
This would have been surely good addition. We should revisit this later.

**Pull request closed without merging**
